name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.3.1-dev

environment:
  sdk: ">=3.10.1 <4.0.0"
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.19
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  messagepack: ^0.2.1
  collection: ^1.19.1
  qr_flutter: ^4.1.0
  provider: ^6.1.5+1
  get_it: ^9.1.1
  p2plib: ^2.3.1
  sss256: ^1.0.0
  intl: ^0.20.2

  # Platform dependent
  flutter_secure_storage: ^10.0.0-beta.5
  flutter_screen_lock: ^9.2.2+2
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  mobile_scanner: ^7.1.3
  p2plib_flutter: ^0.2.0
  path_provider: ^2.1.5
  wakelock_plus: ^1.4.0
  url_launcher: ^6.3.2
  local_auth: ^3.0.0
  share_plus: ^12.0.1
  vibration: ^3.1.4
  hive: ^2.2.3
  nsd: ^4.0.3

  # Analytics
  sentry_flutter: ^9.8.0
  amplitude_flutter: ^4.3.9

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  
  fonts:
    - family: Guardian-Icons
      fonts:
      - asset: assets/fonts/Guardian-Icons.ttf

  assets:
    - assets/images/
    - assets/icons/
